import setuptools

setuptools.setup(
    name="f5_tts",
    packages=setuptools.find_namespace_packages(),
    version="0.1.0",
    author="Yushen Chen and Zhikang Niu and Ziyang Ma and Keqi Deng and Chunhui Wang and Jian Zhao and Kai Yu and Xie Chen",
    description="F5-TTS: A Fairytaler that Fakes Fluent and Faithful Speech with Flow Matching",
    url="https://github.com/SWivid/F5-TTS",
    project_urls={},
    scripts=[],
    include_package_data=True,
    # include txt tokenizers
    package_data={
        "": ["*.txt"],
    },
    install_requires=[
        "torch>=2.0.0",
        "torchaudio>=2.0.0",
        "accelerate>=0.33.0",
        "cached_path @ git+https://github.com/rsxdalv/cached_path@main",
        "click",
        "datasets",
        "einops>=0.8.0",
        "einx>=0.3.0",
        "ema_pytorch>=0.5.2",
        "gradio",
        "jieba",
        "librosa",
        "matplotlib",
        "numpy<=1.26.4",
        "pydub",
        "pypinyin",
        "safetensors",
        "soundfile",
        "tomli",
        "torchdiffeq",
        "tqdm>=4.65.0",
        "transformers",
        "vocos",
        "wandb",
        "x_transformers>=1.31.14",
        "pre-commit",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
